/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as ScrollRouteImport } from './routes/scroll'
import { Route as QuillRouteImport } from './routes/quill'
import { Route as MaskRouteImport } from './routes/mask'
import { Route as HammerRouteImport } from './routes/hammer'
import { Route as EchoRouteImport } from './routes/echo'
import { Route as BestiaryRouteImport } from './routes/bestiary'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuillIndexRouteImport } from './routes/quill/index'
import { Route as QuillWritingToolsRouteImport } from './routes/quill/writing-tools'
import { Route as QuillWorldsRouteImport } from './routes/quill/worlds'
import { Route as QuillWorldObjectsRouteImport } from './routes/quill/world-objects'
import { Route as QuillSettingsRouteImport } from './routes/quill/settings'
import { Route as QuillOverviewRouteImport } from './routes/quill/overview'
import { Route as QuillMapsRouteImport } from './routes/quill/maps'
import { Route as QuillHistoryRouteImport } from './routes/quill/history'
import { Route as QuillHelpAndInfoRouteImport } from './routes/quill/help-and-info'
import { Route as QuillFilesRouteImport } from './routes/quill/files'
import { Route as QuillCampaignsRouteImport } from './routes/quill/campaigns'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollRoute = ScrollRouteImport.update({
  id: '/scroll',
  path: '/scroll',
  getParentRoute: () => rootRouteImport,
} as any)
const QuillRoute = QuillRouteImport.update({
  id: '/quill',
  path: '/quill',
  getParentRoute: () => rootRouteImport,
} as any)
const MaskRoute = MaskRouteImport.update({
  id: '/mask',
  path: '/mask',
  getParentRoute: () => rootRouteImport,
} as any)
const HammerRoute = HammerRouteImport.update({
  id: '/hammer',
  path: '/hammer',
  getParentRoute: () => rootRouteImport,
} as any)
const EchoRoute = EchoRouteImport.update({
  id: '/echo',
  path: '/echo',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryRoute = BestiaryRouteImport.update({
  id: '/bestiary',
  path: '/bestiary',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuillIndexRoute = QuillIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuillRoute,
} as any)
const QuillWritingToolsRoute = QuillWritingToolsRouteImport.update({
  id: '/writing-tools',
  path: '/writing-tools',
  getParentRoute: () => QuillRoute,
} as any)
const QuillWorldsRoute = QuillWorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => QuillRoute,
} as any)
const QuillWorldObjectsRoute = QuillWorldObjectsRouteImport.update({
  id: '/world-objects',
  path: '/world-objects',
  getParentRoute: () => QuillRoute,
} as any)
const QuillSettingsRoute = QuillSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => QuillRoute,
} as any)
const QuillOverviewRoute = QuillOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => QuillRoute,
} as any)
const QuillMapsRoute = QuillMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => QuillRoute,
} as any)
const QuillHistoryRoute = QuillHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => QuillRoute,
} as any)
const QuillHelpAndInfoRoute = QuillHelpAndInfoRouteImport.update({
  id: '/help-and-info',
  path: '/help-and-info',
  getParentRoute: () => QuillRoute,
} as any)
const QuillFilesRoute = QuillFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => QuillRoute,
} as any)
const QuillCampaignsRoute = QuillCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => QuillRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/atlas': typeof AtlasRoute
  '/bestiary': typeof BestiaryRoute
  '/echo': typeof EchoRoute
  '/hammer': typeof HammerRoute
  '/mask': typeof MaskRoute
  '/quill': typeof QuillRouteWithChildren
  '/scroll': typeof ScrollRoute
  '/seed': typeof SeedRoute
  '/vault': typeof VaultRoute
  '/quill/campaigns': typeof QuillCampaignsRoute
  '/quill/files': typeof QuillFilesRoute
  '/quill/help-and-info': typeof QuillHelpAndInfoRoute
  '/quill/history': typeof QuillHistoryRoute
  '/quill/maps': typeof QuillMapsRoute
  '/quill/overview': typeof QuillOverviewRoute
  '/quill/settings': typeof QuillSettingsRoute
  '/quill/world-objects': typeof QuillWorldObjectsRoute
  '/quill/worlds': typeof QuillWorldsRoute
  '/quill/writing-tools': typeof QuillWritingToolsRoute
  '/quill/': typeof QuillIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/atlas': typeof AtlasRoute
  '/bestiary': typeof BestiaryRoute
  '/echo': typeof EchoRoute
  '/hammer': typeof HammerRoute
  '/mask': typeof MaskRoute
  '/scroll': typeof ScrollRoute
  '/seed': typeof SeedRoute
  '/vault': typeof VaultRoute
  '/quill/campaigns': typeof QuillCampaignsRoute
  '/quill/files': typeof QuillFilesRoute
  '/quill/help-and-info': typeof QuillHelpAndInfoRoute
  '/quill/history': typeof QuillHistoryRoute
  '/quill/maps': typeof QuillMapsRoute
  '/quill/overview': typeof QuillOverviewRoute
  '/quill/settings': typeof QuillSettingsRoute
  '/quill/world-objects': typeof QuillWorldObjectsRoute
  '/quill/worlds': typeof QuillWorldsRoute
  '/quill/writing-tools': typeof QuillWritingToolsRoute
  '/quill': typeof QuillIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/atlas': typeof AtlasRoute
  '/bestiary': typeof BestiaryRoute
  '/echo': typeof EchoRoute
  '/hammer': typeof HammerRoute
  '/mask': typeof MaskRoute
  '/quill': typeof QuillRouteWithChildren
  '/scroll': typeof ScrollRoute
  '/seed': typeof SeedRoute
  '/vault': typeof VaultRoute
  '/quill/campaigns': typeof QuillCampaignsRoute
  '/quill/files': typeof QuillFilesRoute
  '/quill/help-and-info': typeof QuillHelpAndInfoRoute
  '/quill/history': typeof QuillHistoryRoute
  '/quill/maps': typeof QuillMapsRoute
  '/quill/overview': typeof QuillOverviewRoute
  '/quill/settings': typeof QuillSettingsRoute
  '/quill/world-objects': typeof QuillWorldObjectsRoute
  '/quill/worlds': typeof QuillWorldsRoute
  '/quill/writing-tools': typeof QuillWritingToolsRoute
  '/quill/': typeof QuillIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/atlas'
    | '/bestiary'
    | '/echo'
    | '/hammer'
    | '/mask'
    | '/quill'
    | '/scroll'
    | '/seed'
    | '/vault'
    | '/quill/campaigns'
    | '/quill/files'
    | '/quill/help-and-info'
    | '/quill/history'
    | '/quill/maps'
    | '/quill/overview'
    | '/quill/settings'
    | '/quill/world-objects'
    | '/quill/worlds'
    | '/quill/writing-tools'
    | '/quill/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/atlas'
    | '/bestiary'
    | '/echo'
    | '/hammer'
    | '/mask'
    | '/scroll'
    | '/seed'
    | '/vault'
    | '/quill/campaigns'
    | '/quill/files'
    | '/quill/help-and-info'
    | '/quill/history'
    | '/quill/maps'
    | '/quill/overview'
    | '/quill/settings'
    | '/quill/world-objects'
    | '/quill/worlds'
    | '/quill/writing-tools'
    | '/quill'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/atlas'
    | '/bestiary'
    | '/echo'
    | '/hammer'
    | '/mask'
    | '/quill'
    | '/scroll'
    | '/seed'
    | '/vault'
    | '/quill/campaigns'
    | '/quill/files'
    | '/quill/help-and-info'
    | '/quill/history'
    | '/quill/maps'
    | '/quill/overview'
    | '/quill/settings'
    | '/quill/world-objects'
    | '/quill/worlds'
    | '/quill/writing-tools'
    | '/quill/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AtlasRoute: typeof AtlasRoute
  BestiaryRoute: typeof BestiaryRoute
  EchoRoute: typeof EchoRoute
  HammerRoute: typeof HammerRoute
  MaskRoute: typeof MaskRoute
  QuillRoute: typeof QuillRouteWithChildren
  ScrollRoute: typeof ScrollRoute
  SeedRoute: typeof SeedRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll': {
      id: '/scroll'
      path: '/scroll'
      fullPath: '/scroll'
      preLoaderRoute: typeof ScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quill': {
      id: '/quill'
      path: '/quill'
      fullPath: '/quill'
      preLoaderRoute: typeof QuillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mask': {
      id: '/mask'
      path: '/mask'
      fullPath: '/mask'
      preLoaderRoute: typeof MaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hammer': {
      id: '/hammer'
      path: '/hammer'
      fullPath: '/hammer'
      preLoaderRoute: typeof HammerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echo': {
      id: '/echo'
      path: '/echo'
      fullPath: '/echo'
      preLoaderRoute: typeof EchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary': {
      id: '/bestiary'
      path: '/bestiary'
      fullPath: '/bestiary'
      preLoaderRoute: typeof BestiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quill/': {
      id: '/quill/'
      path: '/'
      fullPath: '/quill/'
      preLoaderRoute: typeof QuillIndexRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/writing-tools': {
      id: '/quill/writing-tools'
      path: '/writing-tools'
      fullPath: '/quill/writing-tools'
      preLoaderRoute: typeof QuillWritingToolsRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/worlds': {
      id: '/quill/worlds'
      path: '/worlds'
      fullPath: '/quill/worlds'
      preLoaderRoute: typeof QuillWorldsRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/world-objects': {
      id: '/quill/world-objects'
      path: '/world-objects'
      fullPath: '/quill/world-objects'
      preLoaderRoute: typeof QuillWorldObjectsRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/settings': {
      id: '/quill/settings'
      path: '/settings'
      fullPath: '/quill/settings'
      preLoaderRoute: typeof QuillSettingsRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/overview': {
      id: '/quill/overview'
      path: '/overview'
      fullPath: '/quill/overview'
      preLoaderRoute: typeof QuillOverviewRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/maps': {
      id: '/quill/maps'
      path: '/maps'
      fullPath: '/quill/maps'
      preLoaderRoute: typeof QuillMapsRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/history': {
      id: '/quill/history'
      path: '/history'
      fullPath: '/quill/history'
      preLoaderRoute: typeof QuillHistoryRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/help-and-info': {
      id: '/quill/help-and-info'
      path: '/help-and-info'
      fullPath: '/quill/help-and-info'
      preLoaderRoute: typeof QuillHelpAndInfoRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/files': {
      id: '/quill/files'
      path: '/files'
      fullPath: '/quill/files'
      preLoaderRoute: typeof QuillFilesRouteImport
      parentRoute: typeof QuillRoute
    }
    '/quill/campaigns': {
      id: '/quill/campaigns'
      path: '/campaigns'
      fullPath: '/quill/campaigns'
      preLoaderRoute: typeof QuillCampaignsRouteImport
      parentRoute: typeof QuillRoute
    }
  }
}

interface QuillRouteChildren {
  QuillCampaignsRoute: typeof QuillCampaignsRoute
  QuillFilesRoute: typeof QuillFilesRoute
  QuillHelpAndInfoRoute: typeof QuillHelpAndInfoRoute
  QuillHistoryRoute: typeof QuillHistoryRoute
  QuillMapsRoute: typeof QuillMapsRoute
  QuillOverviewRoute: typeof QuillOverviewRoute
  QuillSettingsRoute: typeof QuillSettingsRoute
  QuillWorldObjectsRoute: typeof QuillWorldObjectsRoute
  QuillWorldsRoute: typeof QuillWorldsRoute
  QuillWritingToolsRoute: typeof QuillWritingToolsRoute
  QuillIndexRoute: typeof QuillIndexRoute
}

const QuillRouteChildren: QuillRouteChildren = {
  QuillCampaignsRoute: QuillCampaignsRoute,
  QuillFilesRoute: QuillFilesRoute,
  QuillHelpAndInfoRoute: QuillHelpAndInfoRoute,
  QuillHistoryRoute: QuillHistoryRoute,
  QuillMapsRoute: QuillMapsRoute,
  QuillOverviewRoute: QuillOverviewRoute,
  QuillSettingsRoute: QuillSettingsRoute,
  QuillWorldObjectsRoute: QuillWorldObjectsRoute,
  QuillWorldsRoute: QuillWorldsRoute,
  QuillWritingToolsRoute: QuillWritingToolsRoute,
  QuillIndexRoute: QuillIndexRoute,
}

const QuillRouteWithChildren = QuillRoute._addFileChildren(QuillRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AtlasRoute: AtlasRoute,
  BestiaryRoute: BestiaryRoute,
  EchoRoute: EchoRoute,
  HammerRoute: HammerRoute,
  MaskRoute: MaskRoute,
  QuillRoute: QuillRouteWithChildren,
  ScrollRoute: ScrollRoute,
  SeedRoute: SeedRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
